CREATE TABLE IF NOT EXISTS users(
    id INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL CHECK (LENGTH(username) >= 4),
    password VARCHAR(100) NOT NULL CHECK (LENGTH(password) >= 8),
    role VARCHAR(20) NOT NULL,
    enabled INTEGER DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS note (
    id VARCHAR DEFAULT random_uuid() PRIMARY KEY,
    title VARCHAR(100) NOT NULL CHECK (LENGTH(title) >= 5),
    content VARCHAR(10000) NOT NULL CHECK (LENGTH(title) >= 5),
    access VARCHAR NOT NULL,
    user_id INTEGER NOT NULL,
    created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT note_users FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);